# Generated by Django 2.2.2 on 2019-06-24 21:04

from django.db import migrations
from django.conf import settings
import os
import csv


def data_pull(apps, schema_editor):
    # Category = apps.get_model('shelf', 'Category')
    Book = apps.get_model('shelf', 'Book')
    

    # Book.objects.all().delete()
    # Category.objects.all().delete()

    # category = Category(name="")
    # category.save()

    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')

    with open(filename) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book = Book(title=row['title'], author=row['author'], url_address=row['url'], description=row['description'])
            book.save()

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20190624_1513'),
    ]

    operations = [
        migrations.RunPython(data_pull, do_nothing),
    ]

